#pragma once
#include <xtl.h>
#include <xboxmath.h>
#include <stdio.h>
#include <fstream>
#include <sstream>
#include <map>
#include <xbdm.h>
#include <xkelib.h>
#include <xuiapp.h>
#include <xui.h>
#include <xstring>
#include <string>
#include <time.h>
#include <vector>
#include <array>
#include <ctime>
#include <sys/stat.h>

#include <math.h>
#include "KeyVault.h"
#include "Globals.h"
#include "Utilities.h"
#include "Media.h"
#include "Network.h"
#include "System.h"
#include "TitleHooks.h"
#include "UI.h"
#include "XUI.h"
#include "Settings_Scene.h"
#include "FormatUtils.h"
#include "Globals.h"
#include "IntegrityManager.h"
#include "KVGuard.h"
#include "HUD_UI.h"
#include "Dashboard_Defs.h"
#include "Dashboard_UI.h"
#include "INIPhaser.h"
#include "SimpleINI.h"
#include "games.h"
#include "xzp.h"
#include "Detour.h"
#include "Encrypt.h"

#define BASEADDY 0x90DF0000 
using namespace std;

/*#pragma once
#include <xtl.h>
#include <xboxmath.h>
#include <stdio.h>
#include <fstream>
#include <sstream>
#include <map>
#include <xbdm.h>
#include <xkelib.h>
#include <xuiapp.h>
#include <xui.h>
#include <xstring>
#include <string>
#include <time.h>
#include <vector>
#include <array>
#include <ctime>
#include <sys/stat.h>

#include <math.h>
#include "KeyVault.h"
#include "Globals.h"
#include "Utilities.h"
#include "Media.h"
#include "Network.h"
#include "System.h"
#include "TitleHooks.h"
#include "UI.h"
#include "XUI.h"
#include "Settings_Scene.h"
#include "FormatUtils.h"
#include "Globals.h"
#include "IntegrityManager.h"
#include "KVGuard.h"
#include "HUD_UI.h"
#include "Dashboard_Defs.h"
#include "Dashboard_UI.h"
#include "INIPhaser.h"
#include "SimpleINI.h"
#include "games.h"
#include "xzp.h"
#include "Detour.h"
#define BASEADDY 0x90DF0000 
using namespace std;*/
